### ISSUE TITLE
How to avoid Glitch putting app to sleep

### ISSUE THREAD

**Issue by saschaeggi** [ChromaticHQ/drupalorg-slack#6]
The response from Glitch in Slack is just the "wake up Glitch" all the time – which doesn't render of course. How did you overcome this?

**Comment by markdorison** [comment]
Hi @saschaeggi Glitch [puts apps to sleep after a period of inactivity](https://glitch.com/help/restrictions/):

> Apps sleep after 5 minutes if they are not used, and those running for more than 12 hours are stopped. They wake again upon receiving another HTTP request

To avoid this you can either: 
* Upgrade to their paid plan (or host it elsewhere).
* Send an HTTP request to wake your app before the request where you expect a response. (This is useful when triggering events on a schedule, not so useful if you are using a slash command from Slack).
